"""
app.py — Unified FastAPI prediction service for Eban-Haven ML pipelines.
Serves the Reintegration Readiness, Donor Churn, and Marketing Analysis pipelines.

Start locally:
    uvicorn app:app --host 0.0.0.0 --port 8000
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

_BASE = Path(__file__).parent

# ── Load models at startup ─────────────────────────────────────────────────────

def _load(model_file: str, meta_file: str):
    mp = _BASE / model_file
    mj = _BASE / meta_file
    if not mp.exists():
        raise FileNotFoundError(f"Model not found: {mp}")
    return joblib.load(mp), json.loads(mj.read_text())

_reint_model, _reint_meta   = _load("reintegration_model.joblib",  "reintegration_model_metadata.json")
_churn_model, _churn_meta   = _load("donor_churn_model.joblib",     "donor_churn_metadata.json")

# Marketing analysis metadata (generated by marketing-campaign-analysis.ipynb)
_marketing_meta_path = _BASE / "marketing_analysis_metadata.json"
_marketing_meta: dict = json.loads(_marketing_meta_path.read_text()) if _marketing_meta_path.exists() else {}

# ── App ────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Eban-Haven ML Service",
    description="Reintegration Readiness, Donor Churn, and Marketing Analysis endpoints.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # Narrowed to Azure backend URL in production
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)

# ── Health ─────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {
        "status": "ok",
        "models": {
            "reintegration_readiness": _reint_meta.get("model_version", "1.0.0"),
            "donor_churn":             _churn_meta.get("model_version",  "1.0.0"),
        },
        "analyses": {
            "marketing_campaign": _marketing_meta.get("pipeline_version", "not_run"),
        }
    }

# ── Marketing Campaign Analysis ────────────────────────────────────────────────

@app.get("/marketing/campaign-analysis")
def get_marketing_analysis():
    """
    Returns pre-computed causal estimates from marketing-campaign-analysis.ipynb.
    Re-run the notebook to refresh these results after each campaign.
    Returns 503 if the notebook has not been run yet.
    """
    if not _marketing_meta or _marketing_meta.get("last_run") is None:
        from fastapi import HTTPException
        raise HTTPException(
            status_code=503,
            detail="Marketing analysis has not been run yet. Execute marketing-campaign-analysis.ipynb to generate results."
        )
    return _marketing_meta

# ── Reintegration Readiness ────────────────────────────────────────────────────

class ResidentFeatures(BaseModel):
    resident_id:              Optional[int]   = None
    safehouse_id:             str
    age_at_entry:             int             = Field(..., ge=10, le=25)
    days_in_program:          int             = Field(..., ge=0)
    referral_source:          str
    total_sessions:           float           = Field(..., ge=0)
    pct_progress_noted:       float           = Field(..., ge=0.0, le=1.0)
    pct_concerns_flagged:     float           = Field(..., ge=0.0, le=1.0)
    latest_attendance_rate:   float           = Field(..., ge=0.0, le=1.0)
    avg_progress_percent:     float           = Field(..., ge=0.0, le=100.0)
    avg_general_health_score: float           = Field(..., ge=1.0, le=10.0)
    pct_psych_checkup_done:   float           = Field(..., ge=0.0, le=1.0)
    num_health_records:       float           = Field(..., ge=0)
    total_incidents:          float           = Field(..., ge=0)
    num_severe_incidents:     float           = Field(..., ge=0)
    total_plans:              float           = Field(..., ge=0)
    pct_plans_achieved:       float           = Field(..., ge=0.0, le=1.0)

class ReintegrationResponse(BaseModel):
    resident_id:                Optional[int]
    reintegration_probability:  float
    prediction:                 str
    risk_tier:                  str
    threshold_used:             float

@app.post("/predict/reintegration-readiness", response_model=ReintegrationResponse)
def predict_reintegration(features: ResidentFeatures):
    threshold = _reint_meta["best_threshold"]
    try:
        row  = features.model_dump()
        df   = pd.DataFrame([row])[_reint_meta["feature_columns"]]
        prob = float(_reint_model.predict_proba(df)[0, 1])
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    prediction = "Ready" if prob >= threshold else "Not Ready"
    risk_tier  = "High Readiness" if prob >= 0.70 else ("Moderate Readiness" if prob >= threshold else "Low Readiness")

    return ReintegrationResponse(
        resident_id=features.resident_id,
        reintegration_probability=round(prob, 4),
        prediction=prediction,
        risk_tier=risk_tier,
        threshold_used=round(threshold, 4),
    )

# ── Donor Churn ────────────────────────────────────────────────────────────────

class DonorFeatures(BaseModel):
    supporter_id              : Optional[int]   = None
    days_since_last_donation  : float           = Field(..., ge=0)
    days_since_first_donation : float           = Field(..., ge=0)
    days_since_joined         : float           = Field(..., ge=0)
    total_donations           : float           = Field(..., ge=0)
    pct_recurring             : float           = Field(..., ge=0.0, le=1.0)
    avg_days_between_donations: Optional[float] = Field(None, ge=0)
    total_amount              : float           = Field(..., ge=0)
    avg_amount                : float           = Field(..., ge=0)
    max_amount                : float           = Field(..., ge=0)
    amount_trend              : float           = Field(0.0)
    acquisition_channel       : str
    supporter_type            : str
    relationship_type         : str

class DonorChurnResponse(BaseModel):
    supporter_id      : Optional[int]
    churn_probability : float
    prediction        : str
    risk_tier         : str
    threshold_used    : float
    top_risk_signals  : list[str]

def _churn_risk_signals(f: DonorFeatures) -> list[str]:
    signals = []
    if f.days_since_last_donation > 365:
        signals.append("high_recency")
    if f.pct_recurring == 0.0:
        signals.append("zero_recurring")
    if f.amount_trend < 0:
        signals.append("negative_trend")
    if f.total_donations <= 1:
        signals.append("one_time_only")
    return signals

def _score_churn(features: DonorFeatures) -> DonorChurnResponse:
    threshold = _churn_meta["best_threshold"]
    row  = features.model_dump()
    df   = pd.DataFrame([row])[_churn_meta["feature_columns"]]
    prob = float(_churn_model.predict_proba(df)[0, 1])

    prediction = "At Risk" if prob >= threshold else "Stable"
    risk_tier  = "High Risk" if prob >= 0.75 else ("Moderate Risk" if prob >= threshold else "Low Risk")

    return DonorChurnResponse(
        supporter_id=features.supporter_id,
        churn_probability=round(prob, 4),
        prediction=prediction,
        risk_tier=risk_tier,
        threshold_used=round(threshold, 4),
        top_risk_signals=_churn_risk_signals(features),
    )

@app.post("/predict/donor-churn", response_model=DonorChurnResponse)
def predict_churn(features: DonorFeatures):
    try:
        return _score_churn(features)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

@app.post("/predict/donor-churn-batch", response_model=list[DonorChurnResponse])
def predict_churn_batch(features_list: list[DonorFeatures]):
    """Score multiple supporters in one call. Caller filters by threshold/limit."""
    if not features_list:
        return []
    try:
        rows  = [f.model_dump() for f in features_list]
        df    = pd.DataFrame(rows)[_churn_meta["feature_columns"]]
        probs = _churn_model.predict_proba(df)[:, 1]
        return [
            DonorChurnResponse(
                supporter_id=f.supporter_id,
                churn_probability=round(float(p), 4),
                prediction="At Risk" if float(p) >= _churn_meta["best_threshold"] else "Stable",
                risk_tier="High Risk" if float(p) >= 0.75 else (
                    "Moderate Risk" if float(p) >= _churn_meta["best_threshold"] else "Low Risk"
                ),
                threshold_used=round(_churn_meta["best_threshold"], 4),
                top_risk_signals=_churn_risk_signals(f),
            )
            for f, p in zip(features_list, probs)
        ]
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
